platform :ios, '7.0'
target 'Horoscopes' do
	pod 'GoogleAnalytics', '~> 3.13'
	pod 'Reachability'
	pod 'JSONKit-NoWarning'
	pod 'FBSDKCoreKit'
	pod 'UIImage+animatedGif'
	pod 'MBProgressHUD'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'MZFormSheetController'
    pod 'AsyncDisplayKit'
    pod 'WebASDKImageManager'
    pod 'Google-Mobile-Ads-SDK', '~> 7.4'
    pod 'AFNetworking', '~> 2.6'
    pod 'DateTools'
end